name = "worker-api"
main = "src/index.ts"
compatibility_date = "2023-03-25"

[triggers]
crons = ["*/10 * * * *"]

[vars]
SIAKAD_URL = ""
SLC_URL = ""
LMS_URL = ""
NIM = ""
PASSWORD = ""
NOTIFICATION_API_SECRET = ""
NOTIFICATION_API_BASE_URL = ""

[[kv_namespaces]]
binding = "HYSBYSU_STORAGE"
id = ""
preview_id = ""

[build]
command = "node build.js"