# fly.toml file generated for hysbysu on 2022-12-14T12:14:18+07:00

app = "hysbysu"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
