# fly.toml file generated for hysbysu on 2023-02-22T10:13:36+07:00

app = "hysbysu"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "ghcr.io/elianiva/hysbysu:edge"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
